imports = [
         "programming",
]

[managers.system]
items = [
    
    # FTP
    "git",
    "curl",
    "wget",
    "filezilla",
    "nextcloud-client",
    "transmission-gtk",
    

    #Explorer
    "thunar",
    "thunar-custom-actions",
    "thunar-uca",
    "thunar-vcs-plugin",
    "thunar-shares-plugin",
    "thunar-volman",
    "thunar-archive-plugin",
    "thunar-nextcloud-plugin",


    #Terminals
    "alacritty",
    "kitty",
    "zsh",
    "zsh-autosuggestions",
    
    # Konsolentools
    "zoxide",
    "fd",
    "tmux",
    "starship",
    "btop",
    "nvtop",
    "atuin",
    "tldr",
    "atuin",
    "fastfetch",
    "inotify-tools",
    

    #Hilfstools

    "drawio-desktop-bin",
    "gimp",
    "yt-dlp",
    "cowsay",
    "rustdesk-bin",

  


    #Organisation
    "obsidian",
    "evolution",
    "pomatez",
    "lf",
    "fzf",
    "zoxide",

    
    

    #Unterhaltung
    "spotify-launcher",
    "steam",
    "calibre",
    "freetube",

    #Kommunikation
    "discord",
    "betterbird-de-bin",
    "signal-desktop",
    "element-desktop",
    "tokodon",

    

    #System Relevant
    "firefox",
    "localsend-bin",
    "timeshift",
    "grimshot",
    "mpv",
    "corectrl",
    "keepassxc",
    "protonvpn-gui",
    "rofi-lbonn-wayland",
    "pandoc",
    "netcat",
    "nmap",
    "7-zip-full",
    "partitionmanager",
    "flatpak",


        #Fonts
        "noto-fonts-emoji",


    
    
    #Virtualisierung

    "bottles",


    
]

[managers.cargo]
items = [
    "bacon",
    "nu",
    "exa",
    "du-dust",
    "bat",
    "ripgrep",
    "cargo-info",
    "cargo-update",
    "cargo-expand",
    "cargo-show-asm",
    "irust",
    "speedtest-rs",
    "wiki-tui",
    "mprocs",
    "uwuify",
    "trunk",
    "coreutils",
    "eza",
    "tree-rs",
    "hexyl",
    "nomino",
]