# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
     "programming",
]

# Packages to be installed via the native package manager.
pkg_managers.system.pkgs = [
    
    # FTP
    "git",
    "curl",
    "wget",
    "filezilla",
    "nextcloud-client",
    "transmission-gtk",
    
    #Terminals
    "alacritty",
    "kitty",
    "zsh",
    "zsh-autosuggestions",
    
    # Konsolentools
    "zoxide",
    "fd",
    "tmux",
    "starship",
    "btop",
    "nvtop",
    "atuin",
    "tldr",
    "atuin",
    "fastfetch",
    

    #Hilfstools

    "drawio-desktop-bin",
    "gimp",
    "yt-dlp",
    "cowsay",
    "rustdesk-bin",
    "python-eduvpn-client",
    "7zip",


    #Organisation
    "obsidian",
    "evolution",
    "pomatez",
    "masterpdfeditor",
    "lf",
    "fzf",
    "zoxide",
    "lazygit",
    
    

    #Unterhaltung
    "spotify-launcher",
    "steam",
    "calibre",
    "freetube",

    #Kommunikation
    "discord",
    "betterbird-de-bin",
    "signal-desktop",
    "element-desktop",
    "tokodon",

    

    #System Relevant
    "firefox",
    "localsend-bin",
    "timeshift",
    "grimshot",
    "mpv",
    "corectrl",
    "keepassxc",
    "protonvpn-gui",
    "rofi-lbonn-wayland",
    "pandoc",
    "netcat",
    "protonmail-bridge",
    "7-zip-full",
    "partitionmanager",
    "flatpak",
    "transmission-gtk",

        #Fonts
        "noto-fonts-emoji",


    
    
    #Virtualisierung

    "bottles",
    "docker",
    "docker-compose",

    
]

# Packages to be installed via Flatpak.
pkg_managers.flatpak.pkgs = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
pkg_managers.cargo.pkgs = [
    "bacon",
    "nu",
    "exa",
    "du-dust",
    "bat",
    "ripgrep",
    "cargo-info",
    "cargo-update",
    "cargo-expand",
    "cargo-show-asm",
    "irust",
    "speedtest-rs",
    "wiki-tui",
    "mprocs",
    "uwuify",
    "trunk",
    "coreutils",
    "eza",
    "tree-rs",
    "hexyl",
    "nomino",
    "tree-rs",
    "lazygit",

]
