# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    "amd_gpu",
    "cad",
    "cargo_install",
    "core_packages",
    "docker",
    "entertainment",
    "file_managment",
    "hypr",
    "latex",
    "multimedia",
    "nvdia_gpu",
    "office",
    "programming",
    "remote_control",
    "security",
    "shell",
    "virt-manager",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    "zsa-keymapp-bin", # ZSA Keyboard Configuration Tool
    "corectrl",        # AMD GPU Konfigurationstool
    "cuda",            # CUDA-Support für NVIDIA GPU
    "optimus-manager", # GPU-Switching-Management für Multi-GPU-Setups
    "btrfs-assistant", # Btrfs-Management-Tool für Subvolumes und Snapshots
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
