# --------------------------- #
#    Manager Configuration    #
# --------------------------- #

add = "paru -S --noconfirm --needed #:?"
remove = "paru -Rns --noconfirm #:?"
sync = "paru -Syy --noconfirm"
upgrade = "paru -Syu --noconfirm"


plural_name = "system packages"

hook_name = "system_packages" # This is used in hooks. (Example: post_system_packages_add)

# ------------------------------- #
#    Additional configuration.    #
# ------------------------------- #

[config]
many_args = true
