# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
[managers.system]
items = [
    #AMD-Grafik
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",

    #Krypto
    "picocrypt-git",
    "veracrypt-inyourlanguage",
    "tor-browser-bin",

    #Hyprland
    "hyprcursor-dracula-kde-git",

    #Lab
    "arduino",
    "kicad",
    "remmina",
    "freerdp",
    "orca-slicer",

    #Audio
    "noisetorch",

    #Virtualisierung
    "qemu-full",
    "virt-manager",
    "virt-viewer",
    "dnsmasq",
    "bridge-utils",
    "monero-gui",
    "docker",
    "docker-compose",
    "buildx",
    "docker-buildx"
]

# Packages to be installed via Flatpak.
[managers.flatpak]
items= [

]

# Packages to be installed via Cargo.
[managers.cargo]
items = [
    # "bacon",
]
