# --------------------- #
#    Generation File    #
# --------------------- #

# Other generation files to import. (Example: intensive_apps -> ~/.config/rebos/imports/intensive_apps.toml)
imports = [
    # "intensive_apps",
]

# Packages to be installed via the native package manager.
pkg_managers.system.pkgs = [
    #AMD-Grafik
    "xf86-video-amdgpu",
    "vulkan-radeon",
    "lib32-vulkan-radeon",


    #Lab
    "arduino",
    "kicad",
    "cura-bin",

    #Audio
    "noisetorch",

        #Virtualisierung
    "qemu-full",
    "virt-manager",
    "virt-viewer",
    "dnsmasq",
    "bridge-utils",    
]

# Packages to be installed via Flatpak.
pkg_managers.flatpak.pkgs = [
    # "com.github.tchx84.Flatseal",
]

# Packages to be installed via Cargo.
pkg_managers.cargo.pkgs = [
    # "bacon",
]
