[managers.cargo]
items = [
    "cargo-watch",
    "cargo-edit",
    "cargo-expand",
    "cargo-outdated",
    "cargo-audit",
    "cargo-tarpaulin",
    "cargo-tree",
    "cargo-nextest",
    "cargo-make",
    "bacon",
    "bat",
    "coreutils",
    "cross",
    "dioxus-cli",
    "du-dust",
    "evcxr",
    "hexyl",
    "irust",
    "mprocs",
    "nomino",
    "ripgrep",
    "rebos",
    "tauri-cli",
    "tree-rs",
    "trunk",
    "uwuify",
    "krabby",

]
