[managers.system]
items = [
  "nvidia-container-toolkit", # Unterst端tzung f端r NVIDIA-GPUs in Docker-Containern
  "nvidia-dkms",              # NVIDIA-Grafiktreiber mit Dynamic Kernel Module Support
  "nvidia-utils",             # Dienstprogramme und Bibliotheken f端r NVIDIA-Treiber
  "nvtop",                    # GPU-Prozess-Monitor f端r NVIDIA-GPUs
]
