pkg_managers.system.pkgs = [
  # Rust
  "rustup",
  "rust-analyzer",
  "rust-src",

  # Python
  "python",
  "python-pip",
  "python-pipx",

  #R
  "r",

  #Editors
  "neovim",
  "emacs",
  "visual-studio-code-bin",
  "helix",

  #Language Servers
  "ansible-language-server",
  "bash-language-server",
  "vscode-langservers-extracted",
  "dockerfile-language-server",
  "markdown-oxide-git",
  "python-lsp-server",
  "typescript-language-server",
  
  
  #Extras
  "jupyterlab",
  "ansible",
]


pkg_managers.cargo.pkgs = [
  "taplo-cli",
  "evcxr",
  "evcxr_jupyter",
  
]
