[managers.system]
items = [
  #Erlang-Based
  "elixir",
  # Julia
  "juliaup",
  # Rust
  "rustup",
  "rust-analyzer",
  "rust-src",

  # Python
  "python",
  "python-pip",
  "python-pipx",
  "poetry",

  #R
  "r",

  #Editors
  "neovim",
  "visual-studio-code-bin",
  "helix",
  "zed-editor",

  #Language Servers
  "ansible-language-server",
  "bash-language-server",
  "vscode-langservers-extracted",
  "dockerfile-language-server",
  "markdown-oxide-git",
  "python-lsp-server",
  "typescript-language-server",
  
  
  #Extras
  "jupyterlab",
  "ansible",
]


[managers.cargo]
items = [
  "taplo-cli",
  "evcxr",
  "evcxr_jupyter",
  "zellij",
]
